version: "3.9"

# TO-DO erase volumes
# docker run -it --network dis -v /home/alurquiza/Alben/1-carrera/4to/SD/Proyecto/distributed_search_engine_with_ml:/app distributed sh
# docker build -t distributed .

services:
  client:
    image: distributed
    container_name: app1
    volumes:
      - /home/alurquiza/Alben/1-carrera/4to/SD/Proyecto/distributed_search_engine_with_ml:/app
    command: bash script.sh 10.5.0.2 docs-lisa
    # command: bash -c "
    #   python3 run_server.py --ip 10.5.0.2 --collection lisa-docs &&
    #   python3 run_client.py --ip 10.5.0.2 && 
    #   python3 -m http.server --d dist/ 8001"
    networks:
      dis:
        ipv4_address: 10.5.0.2

  server1:
    image: distributed
    container_name: app2
    volumes:
      - /home/alurquiza/Alben/1-carrera/4to/SD/Proyecto/distributed_search_engine_with_ml:/app
    command: bash script.sh 10.5.0.3 npl
    networks:
      dis:
        ipv4_address: 10.5.0.3

  server2:
    image: distributed
    container_name: app3
    volumes:
      - /home/alurquiza/Alben/1-carrera/4to/SD/Proyecto/distributed_search_engine_with_ml:/app
    command: bash script.sh 10.5.0.4 npl
      # python3 run_client.py --ip 10.5.0.4 && 
    networks:
      dis:
        ipv4_address: 10.5.0.4


networks:
  dis:
    name: dis
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
