
PEER_EXPIRY = 10

PING_PORT_NUMBER = 2524
PING_RESPONSE_PORT_NUMBER = 2525
PING_MSG_SIZE    = 1
PING_INTERVAL    = 1  # Once per second

CLI_SERV_PORT_NUMBER = 2526

DEBUG_MODE = False

WAIT_TIME_FOR_REQUEST = 5

AMOUNT_DOCS_IN_RESPONSE = 20

ORIGINS_API_CLIENT = [
    "http://localhost",
    "http://localhost:8000",
    "http://localhost:8001",
]